### ISSUE TITLE
Frontend: Handlebar files

### ISSUE THREAD

**Issue by AaronGoldsmith** [AaronGoldsmith/stock-wars#14]
### There are a few issues with the **.handlebar** files.  
 

The `main.handlebars` file is way too busy as of now. The code should be fairly lightweight and you should be implementing **handlebar partials**. Check out the [docs ](https://handlebarsjs.com/partials.html) and this [walkthrough](http://hackersandslackers.com/handlebars-templating-in-expressjs/) for more info.

Your main file is supposed to act as the overall layout, while the `index.handlebars` and `members.handlebars` views are used to render the content.

**Comment by jayhua97** [comment]
Will fix it right up.
